import 'package:ado_dad_admin/features/vehicle_company/bloc/vehicle_company_bloc.dart';
import 'package:ado_dad_admin/models/vehicle_company_model.dart';
import 'package:country_picker/country_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';

class VehicleCompanyAdd extends StatefulWidget {
  const VehicleCompanyAdd({super.key});

  @override
  State<VehicleCompanyAdd> createState() => _VehicleCompanyAddState();
}

class _VehicleCompanyAddState extends State<VehicleCompanyAdd> {
  final GlobalKey<FormState> _companyFormKey = GlobalKey<FormState>();

  List<String> _countryList = [];
  final List<String> _vehicleTypes = ["TWO_WHEELER", "FOUR_WHEELER"];

  String _name = '';
  String _logo = '';
  String? _origincountry;
  String? _vehicletype;

  @override
  void initState() {
    super.initState();
    _loadCountries(); // Load countries when screen initializes
  }

  Future<void> _loadCountries() async {
    List<String> countries =
        CountryService().getAll().map((country) => country.name).toList();

    setState(() {
      _countryList = countries;
    });
  }

  void _addVehicleCompany() {
    if (_companyFormKey.currentState!.validate()) {
      _companyFormKey.currentState!.save();

      final newVehicleCompany = VehicleCompanyModel(
        id: '', // ID will be generated by backend
        name: _name,
        logo: _logo,
        originCountry: _origincountry!,
        vehicleType: _vehicletype!,
      );
      print('newVehicleCompany:...... $newVehicleCompany');
      context.read<VehicleCompanyBloc>().add(
          VehicleCompanyEvent.addVehicleCompany(
              vehicleCompanyData: newVehicleCompany));
      // context.read<VehicleCompanyBloc>().add(UpdateUser(updatedUser: newUser));

      Future.delayed(const Duration(milliseconds: 500), () {
        _showSuccessPopup(
            context, "Vehicle Company has been added successfully.");
      });
    }
  }

  void _showSuccessPopup(BuildContext context, String message) {
    showDialog(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text("Success"),
          content: Text(message),
          actions: [
            TextButton(
              onPressed: () {
                context.pop();
                context.go('/vehicle-companies');
              },
              child: const Text("OK"),
            ),
          ],
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<VehicleCompanyBloc, VehicleCompanyState>(
      builder: (context, state) {
        return Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            children: [
              _buildHeaderSection(),
              const SizedBox(height: 30),
              _buildVehicleCompanyForm(state),
            ],
          ),
        );
      },
    );
  }

  Widget _buildHeaderSection() {
    return Padding(
      padding: const EdgeInsets.all(15),
      child: Container(
        decoration: BoxDecoration(
          color: Colors.black,
          borderRadius: BorderRadius.circular(12),
        ),
        padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
        child: Row(
          children: [
            IconButton(
              icon: const Icon(Icons.arrow_back_ios_new, color: Colors.white),
              onPressed: () {
                context.pop();
                context
                    .read<VehicleCompanyBloc>()
                    .add(FetchAllVehicleCompany());
              },
            ),
            const Padding(
              padding: EdgeInsets.all(8.0),
              child: Text(
                "Add Vehicle Company",
                style: TextStyle(
                    color: Colors.white,
                    fontSize: 18,
                    fontWeight: FontWeight.bold),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Center _buildVehicleCompanyForm(VehicleCompanyState state) {
    return Center(
      child: SizedBox(
        width: 500,
        child: Card(
          elevation: 5,
          shape:
              RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          child: Padding(
            padding: const EdgeInsets.all(20),
            child: Form(
              key: _companyFormKey,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _buildFormField(
                      "Company Name", "", (value) => _name = value!),
                  const SizedBox(height: 15),
                  _buildFormField(
                      "Company Logo", "", (value) => _logo = value!),
                  const SizedBox(height: 15),
                  _buildDropdownField(
                      "Origin of Country", _origincountry, _countryList,
                      (value) {
                    setState(() => _origincountry = value!);
                  }),
                  const SizedBox(height: 15),
                  _buildDropdownField(
                      "Vehicle Type", _vehicletype, _vehicleTypes, (value) {
                    setState(() => _vehicletype = value!);
                  }),
                  const SizedBox(height: 20),
                  SizedBox(
                    width: double.infinity,
                    child: ElevatedButton(
                      style: ElevatedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(vertical: 12),
                        backgroundColor: Colors.black,
                        foregroundColor: Colors.white,
                        shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(8)),
                      ),
                      onPressed: state is VehicleCompanyLoading
                          ? null
                          : _addVehicleCompany,
                      child: state is VehicleCompanyLoading
                          ? const SizedBox(
                              height: 20,
                              width: 20,
                              child: CircularProgressIndicator(
                                  strokeWidth: 2, color: Colors.white),
                            )
                          : const Text("Add Vehicle Company",
                              style: TextStyle(
                                  fontSize: 16, fontWeight: FontWeight.bold)),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildFormField(
    String label,
    String initialValue,
    Function(String?) onSaved,
  ) {
    return TextFormField(
      decoration: InputDecoration(
        labelText: label,
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
      ),
      validator: (value) {
        if (value == null || value.isEmpty) {
          return "$label is required";
        }
        return null;
      },
      onSaved: onSaved,
    );
  }

  Widget _buildDropdownField(String label, String? selectedValue,
      List<String> items, Function(String?) onChanged) {
    return DropdownButtonFormField<String>(
      value: selectedValue,
      decoration: InputDecoration(
        labelText: label,
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
      ),
      items: items
          .map((type) => DropdownMenuItem(value: type, child: Text(type)))
          .toList(),
      onChanged: onChanged,
      validator: (value) {
        if (value == null || value.isEmpty) {
          return "$label is required";
        }
        return null;
      },
    );
  }
}
