name: Deploy Flutter Web to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            set -e

            cd /var/www/html/ado-dad-web
            git stash
            git pull origin main

            FLUTTER="/home/ubuntu/development/flutter/bin/flutter"
            [ -x "$FLUTTER" ] || { echo "flutter not found at $FLUTTER"; exit 127; }
            export PATH="/home/ubuntu/development/flutter/bin:$PATH"

            "$FLUTTER" --version
            "$FLUTTER" pub get
            "$FLUTTER" build web --release
            git stash clear 

            sudo nginx -t && sudo systemctl reload nginx
