name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: SSH and Deploy
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_ADO_DAD_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_ADO_DAD_SSH_KEY }}
          port: 22
          script: |
            set -e  # Stop the script on errors
            export PATH="$PATH:/usr/local/flutter/bin"  # Add Flutter to PATH
            cd /var/www/html/ado_dad_admin || exit
            git reset --hard  # Reset any local changes
            git pull origin main
            flutter clean  # Clean old builds
            flutter build web --release  # Build Flutter web release
            sudo systemctl reload nginx  # Reload Nginx to apply changes
