name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_ADO_DAD_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_ADO_DAD_SSH_KEY }}
          script: |
            echo "${{ secrets.EC2_ADO_DAD_SSH_KEY }}" > /tmp/key.pem
            chmod 400 /tmp/key.pem
            ssh -o StrictHostKeyChecking=no -i /tmp/key.pem ubuntu@${{ secrets.EC2_ADO_DAD_HOST }} << 'EOF'
              source ~/.bashrc  # Force load .bashrc
              export PATH="$PATH:/usr/local/flutter/bin"
              cd /var/www/html/ado_dad_admin
              git pull origin main
              flutter build web
              sudo systemctl reload nginx
            EOF
            rm -f /tmp/key.pem
